### ISSUE TITLE
Wrong form for Latvian language

### ISSUE THREAD

**Issue by h2u** [jurchiks/numbers2words#5]
`Speller::spellCurrency(37.60, Speller::LANGUAGE_LATVIAN, Speller::CURRENCY_EURO, false)`

returns "trīsdesmit septiņi eiro un 60 **centu**", but should be "**centi**" or im wrong? :)

**Comment by jurchiks** [comment]
I'm not really sure, because the the official guide (http://www.eiro.lv/files/upload/files/Eiro_rakstiba-1.pdf) does not say how to correctly spell specific conjugations of the decimal part, but for whole numbers the rule is "if the number ends with 0 - third form" (e.g. https://img.ma-shops.com/aurich/pic/lettland_20_latu_1992_bn_.jpg), so I just went with the whole number form for the decimal part.
Just to be sure, I asked in a forum I frequent, we'll see what they say, but if you set the currency to LATS and the amount to 20.60, for example, you'd get "divdesmit latu un 60 santīmu", which looks normal as compared to "20 latu 60 santīm**i**". I know the whole number spelling is correct.

**Comment by h2u** [comment]
Maybe you are right. I just noticed that in invoices i see:

- viens simts astoņpadmit eiro, 99 centi
- Septiņi euro un septiņi centi 
- astoņi eiro, 80 centi
- pieci eiro, 47 centi

**Comment by jurchiks** [comment]
Well, they probably just took the official guide literally, as in, no other form of "centi" allowed (even though "0 centu" is the only grammatically correct form for 0). Also, the comma between them is usually not the right form, because they're not separate, they come together, hence the "un".

**Comment by jurchiks** [comment]
Basically, fuck those guys who don't know the basic grammar rule - "if a number ends with 0 (equivalent to divisible by 10 without remainder) - third form".
